apiVersion: batch/v1
kind: CronJob
metadata:
  name: reporting-job
spec:
  schedule: "*/2 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: reporting-job
              image: k8s-job-example:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure