spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: javatechie4u@gmail.com
    password: <GMAIL APP PASSWORD>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
